### ISSUE TITLE
[SURE-9775] vsphere provider and missing credentials_keys

### ISSUE THREAD

**Issue by thehejik** [rancher/turtles#1109]
### What steps did you take and what happened?

Latest Turtles v0.17.0-rc.0 and capi-ui 0.8.2 on local rancher:v2.10-head

There is a `Credential keys missing` message in vsphere CAPIProvider resource after providing vsphere secret when provisioning vsphere provider over capi-ui.

```
$ k get capiproviders.turtles-capi.cattle.io  -n capv-system vsphere -o yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
spec:
  configSecret:
    name: vsphere-credentials-rctrb
  credentials:
    rancherCloudCredentialNamespaceName: cattle-global-data:cc-rc28p
  features:
    clusterResourceSet: true
    clusterTopology: true
    machinePool: true
  name: vsphere
  type: infrastructure
  variables: {}
status:
  conditions
  - lastTransitionTime: "2025-02-26T16:25:27Z"
    message: 'Credential keys missing: [key not found: vmwarevsphere-password, key
      not found: vmwarevsphere-username]'
    reason: RancherCredentialKeyMissing
    severity: Error
    status: "False"
    type: RancherCredentialsSecretMapped
  contract: v1beta1
  installedVersion: v1.12.0
  name: vsphere
  observedGeneration: 2
  phase: Ready
  variables:
    CLUSTER_TOPOLOGY: "true"
    EXP_CLUSTER_RESOURCE_SET: "true"
    EXP_MACHINE_POOL: "true"
```
Seems `RancherCredentialsSecretMapped` is expecting `vmwarevsphere-password` and `vmwarevsphere-username` but the credentials secret we create when provisioning the vsphere provider consists of:
```
apiVersion: v1
data:
  vmwarevspherecredentialConfig-password: XXX
  vmwarevspherecredentialConfig-username: XXX
  vmwarevspherecredentialConfig-vcenter: XXX
  vmwarevspherecredentialConfig-vcenterPort: XXX
kind: Secret
...
```

Also secret `capv-manager-bootstrap-credentials` is empty then:
![Image](https://github.com/user-attachments/assets/de196e30-0d12-4b58-965f-76384d61ed0b)

Anyway vsphere provider is Ready and I could provision a capv cluster but most probably due to my custom resources where credentials are passed in a different way and not using the secret.
