### ISSUE TITLE
Incompatible fleet version getting installed

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#1205]
### What steps did you take and what happened?

Incompatible fleet version getting installed probably by CAAPF, on Rancher version [2.10.2](https://turtles.docs.rancher.com/turtles/next/en/tutorials/quickstart.html#_prerequisites) with turtles v0.18.0-rc.0
https://github.com/rancher/charts/blob/dev-v2.11/charts/fleet/106.0.0%2Bup0.12.0/Chart.yaml#L11

![Image](https://github.com/user-attachments/assets/cca921ad-31a2-4914-a223-24c4a68bcbe7)

### What did you expect to happen?

Fleet version compatibility to be maintained.

### Rancher Turtles version

Rancher - v2.10.2
Turtles - v0.18.0-rc.0

### Label(s) to be applied

/kind bug

**Comment by cpinjani** [comment]
Attaching logs
[logs.tar.gz](https://github.com/user-attachments/files/19465363/logs.tar.gz)

**Comment by Danil-Grigorev** [comment]
@cpinjani Does it affect any functionality? The chart is installed from upstream location, and has same values as the original, and the version installed is inherited from the previous chart. It may be fixed by changing the chart repo source (maybe name only), but is this version naming scheme important in this case?

**Comment by cpinjani** [comment]
Doesn't seem to affect any functionality, also version format is fine on Rancher v2.11

![Image](https://github.com/user-attachments/assets/fbd2f8d5-f08f-4626-915d-68728457c08d)

**Comment by thehejik** [comment]
Hopefully it doesn't have any side effect but as @cpinjani already mentioned the chart version of fleet is different than version of fleet-crd in rancher v2.10 with releases turtles v0.18.0. Not sure how this will behave in sense of rancher upgrades.

![Image](https://github.com/user-attachments/assets/53f415c3-7180-47af-a86d-f20e6310e89c)

**Comment by thehejik** [comment]
There are some differences, for eg. in Rancher Fleet App you can select custom registry mirror but for the upstream one you can't (missing questions.yaml?) also the used values are different.

![Image](https://github.com/user-attachments/assets/3a564e94-1b4c-48c6-a6bc-b065e106d122)

<details>
 <summary>Values from Rancher Fleet App </summary>

```yaml
agent:
  reconciler:
    workers:
      bundledeployment: '50'
      drift: '50'
agentCheckinInterval: 15m
agentImage:
  imagePullPolicy: IfNotPresent
  repository: rancher/fleet-agent
  tag: v0.11.5
agentTLSMode: strict
apiServerCA: |-
  -----BEGIN CERTIFICATE-----
  MIIBvjCCA....
  -----END CERTIFICATE-----
apiServerURL: https://REDACTEDnip.io
bootstrap:
  agentNamespace: cattle-fleet-local-system
  branch: master
  enabled: false
  namespace: fleet-local
  paths: ''
  repo: ''
  secret: ''
controller:
  reconciler:
    workers:
      bundle: '50'
      bundledeployment: '50'
      cluster: '50'
      clustergroup: '50'
      gitrepo: '50'
      imagescan: '50'
debug: false
debugLevel: 0
disableSecurityContext: false
garbageCollectionInterval: 15m
gitClientTimeout: 30s
gitops:
  enabled: true
  syncPeriod: 2h
global:
  cattle: {}
ignoreClusterRegistrationLabels: false
image:
  imagePullPolicy: IfNotPresent
  repository: rancher/fleet
  tag: v0.11.5
leaderElection:
  leaseDuration: 30s
  renewDeadline: 25s
  retryPeriod: 10s
metrics:
  enabled: true
migrations:
  clusterRegistrationCleanup: true
  gitrepoJobsCleanup: true
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
nodeSelector: {}
priorityClassName: rancher-critical
propagateDebugSettingsToAgents: true
tolerations: null
extraEnv:
  - name: EXPERIMENTAL_OCI_STORAGE
    value: 'true'
  - name: EXPERIMENTAL_HELM_OPS
    value: 'true'
gitjob:
  priorityClassName: rancher-critical

```

</details>
<details>
 <summary>Values from upstream Fleet chart </summary>

```yaml
agentTLSMode: strict
apiServerCA: |-
  -----BEGIN CERTIFICATE-----
  MIIBvjCCA....
  -----END CERTIFICATE-----
apiServerURL: https://REDACTED
bootstrap:
  agentNamespace: cattle-fleet-local-system
  enabled: false
extraEnv:
  - name: EXPERIMENTAL_OCI_STORAGE
    value: 'true'
  - name: EXPERIMENTAL_HELM_OPS
    value: 'true'
gitjob:
  priorityClassName: rancher-critical
gitops:
  enabled: true
global:
  cattle:
    systemDefaultRegistry: ''
priorityClassName: rancher-critical
tolerations: null

```

</details>
