### ISSUE TITLE
AKS System MachinePool nodes are reported as Worker nodes

### ISSUE THREAD

**Issue by anmazzotti** [rancher/turtles#1298]
### What steps did you take and what happened?

When importing a AKS Cluster into Rancher, the "System" nodes are reported as **Worker**
In the picture the `pool0` was defined as:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}-pool0"
  namespace: default
spec:
  mode: System
  name: pool0
  sku: Standard_Ds2_v2
```

![Image](https://github.com/user-attachments/assets/fc63d5f6-9791-4c67-928c-49577c743a4f)

### What did you expect to happen?

This reflects how AKS works internally, by having `System` and `User` nodepools. 
It's probably technically correct that Rancher reports all as `Worker`, however this can be confusing for the user.

It would be great if there was a way to correct the Role for this case.

### Label(s) to be applied

/kind bug
