### ISSUE TITLE
Can not override CAPIProvider container image

### ISSUE THREAD

**Issue by anmazzotti** [rancher/turtles#1419]
### What steps did you take and what happened?

This applies to certified providers. 
For example when editing one:

```yaml
kind: CAPIProvider
metadata:
  name: fleet
  namespace: rancher-turtles-system
spec:
  deployment:
    containers:
    - imageUrl: ttl.sh/60043241-9be1-4273-b9c1-5011f45339f8:24h
      name: manager
    - imageUrl: ttl.sh/60043241-9be1-4273-b9c1-5011f45339f8:24h
      name: helm-manager
```

The related Deployment fails due to lookup to `registry.suse.com/rancher/60043241-9be1-4273-b9c1-5011f45339f8:24h`. 

The registry is overridden as specified in here: https://github.com/rancher/turtles/blob/release-0.20/internal/controllers/clusterctl/config.yaml#L72

Unfortunately this ConfigMap is hardcoded and I assume always reconciled as it is. Manually editing the ConfigMap is not possible on the management Cluster, as all changes will be discarded. 

There is no way to remove the override.

### What did you expect to happen?

It should be possible to set a custom imageUrl for any certified and not certified CAPIProvider.

### Rancher Turtles version

0.20.0

### Label(s) to be applied

/kind bug
