### ISSUE TITLE
Can not override registry with ClusterctlConfig

### ISSUE THREAD

**Issue by anmazzotti** [rancher/turtles#1441]
### What steps did you take and what happened?

```
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: rancher-turtles-system
spec:
  providers:
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.16.0/control-plane-components.yaml"
    type: ControlPlaneProvider
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.16.0/bootstrap-components.yaml"
    type: BootstrapProvider
  images:
  - name: control-plane-rke2
    repository: "ghcr.io/rancher"
  - name: bootstrap-rke2
    repository: "ghcr.io/rancher"
  - name: rke2
    repository: "ghcr.io/rancher"
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-control-plane
  namespace: default
spec:
  name: rke2
  type: controlplane
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-bootstrap
  namespace: default
spec:
  name: rke2
  type: bootstrap
```

Tested on Turtles 0.20
Unfortunately there is no documentation for `images` usage.

I tried to align it with the [embedded](https://github.com/rancher/turtles/blob/main/internal/controllers/clusterctl/config.yaml#L56) one, but clearly I do not understand how to use it.

- Shouldn't just be `rke` name? 
- Where do `control-plane-` and `bootstrap-` (or `infrastructure-`) prefixes come from in the embedded config?
- I tried multiple ways, also the full image name for example `cluster-api-provider-rke2-controlplane`.
- The version override works, just not the repository override, it's still stuck to `registry.suse.com/rancher`

### What did you expect to happen?

Should just work in a user friendly way and it should document how.

### Label(s) to be applied

/kind bug

**Comment by anmazzotti** [comment]
Use error it seems. 

```
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: rancher-turtles-system
spec:
  providers:
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.16.0/control-plane-components.yaml"
    type: ControlPlaneProvider
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.16.0/bootstrap-components.yaml"
    type: BootstrapProvider
  images:
  - name: control-plane-rke2
    repository: "ghcr.io/rancher"
  - name: bootstrap-rke2
    repository: "ghcr.io/rancher"
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-control-plane
  namespace: default
spec:
  name: rke2
  type: controlplane
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-bootstrap
  namespace: default
spec:
  name: rke2
  type: bootstrap
```

This works. It may take some time however to reconcile.
Also added to the documentation: https://github.com/rancher/turtles-docs/pull/315
