### ISSUE TITLE
Rancher Turtles installation via UI fails if Cluster API operator already installed

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#450]
### What steps did you take and what happened?

**Steps:**
- Install Rancher and Cluster API operator with Helm: https://docs.rancher-turtles.com/docs/getting-started/install_capi_operator#install-manually-with-helm-alternative

- On Rancher manager UI, navigate to local cluster > Apps > Repositories > Add RT repo

- Goto Charts > Apps > search Turtles > deselect "Enable Cluster API operator" > Install
![image](https://github.com/rancher/turtles/assets/73099870/6880457e-08bf-4a09-a77e-746ad680ac44)

**Logs**
_Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install rancher-turtles/templates/core-provider.yaml failed: 1 error occurred:
2024-03-27T09:12:06.283930774Z 	* object is being deleted: namespaces "capi-system" already exists_

**YAML**
```
cluster-api-operator:
  cert-manager:
    enabled: false
  cluster-api:
    configSecret:
      defaultName: capi-env-variables
      name: ''
    core:
      fetchConfig:
        selector: ''
        url: ''
      namespace: capi-system
    enabled: true
    kubeadmBootstrap:
      fetchConfig:
        selector: ''
        url: ''
      namespace: capi-kubeadm-bootstrap-system
    kubeadmControlPlane:
      fetchConfig:
        selector: ''
        url: ''
      namespace: capi-kubeadm-control-plane-system
    version: v1.4.6
  enabled: false
rancherTurtles:
  features:
    embedded-capi:
      disabled: true
    rancher-kubeconfigs:
      label: true
    rancher-webhook:
      cleanup: true
      kubectlImage: rancher/kubectl
    default: false
  image: registry.rancher.com/rancher/rancher-sandbox/rancher-turtles
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  imageVersion: sha256:cbb4166623d947f947248060694b943580797875ea3e9dedf3d2783df60b9e83
  managerArguments: []
  namespace: rancher-turtles-system
```

### What did you expect to happen?

Rancher Turtles installation via UI should succeed if Cluster API operator already installed
cc: @richardcase 

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

Nightly chart - 61db65a
Rancher v2.8.2

### Anything else you would like to add?

Installation from Backend works https://docs.rancher-turtles.com/docs/getting-started/install_turtles_operator#install-rancher-turtles-operator-without-cluster-api-operator-as-a-helm-dependency

### Label(s) to be applied

/kind bug
