### ISSUE TITLE
Unable to enable Azure CAPIProvider

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/turtles#483]
### What steps did you take and what happened?

The Azure CAPIProvider fails to enable correctly in the 0.4.0 capi ui. The status changes from `Provisioning` to `Ready` but eventually becomes `Unavailable`. The capz-controller-manager pod is in CrashLoopBackoff with the error 

> “failed to get informer from cache” err=“failed to get API group resources: unable to retrieve the complete list of server APIs: [bootstrap.cluster.x-k8s.io/v1beta1](http://bootstrap.cluster.x-k8s.io/v1beta1): the server could not find the requested resource” logger=“controller-runtime.source.EventHandler”

### What did you expect to happen?

I would expect the capz-controller-manager pod to be running and azure capiprovider resource to be in Ready state

### Label(s) to be applied

/kind bug

**Comment by salasberryfin** [comment]
Hi @mantis-toboggan-md, thanks for reporting this. I was able to reproduce the issue with the following configuration:
- Rancher v2.8.2
- Rancher Turtles v0.7.0
- Rancher Turtles UI v0.4.0

Looks like this may be related to missing resources that are added when installing the Kubeadm provider (which is no longer installed together with Turtles, as it was substituted by CAPRKE2).

I did apply this yaml file before installing CAPZ:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: kubeadm-bootstrap
  namespace: capi-kubeadm-bootstrap-system
spec:
  name: kubeadm
  type: bootstrap
  version: v1.4.6
  configSecret:
    name: variables
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: kubeadm-control-plane
  namespace: capi-kubeadm-control-plane-system
spec:
  name: kubeadm
  type: controlPlane
  version: v1.4.6
  configSecret:
    name: variables
```

And then the Azure provider was successfully installed via Rancher UI and the controller did not report any errors.

We'll be investigating this a bit further to propose a solution.
