### ISSUE TITLE
Unable to enable GCP CAPIProvider with Rancher CloudCredentials

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#510]
### What steps did you take and what happened?

GCP CAPIProvider fails to enable using Rancher CloudCredentials. It enables when only ConfigSecret is provided along with GCP_B64ENCODED_CREDENTIALS variable.

- Create GCP Cloud credentials In Rancher
- Create CAPIProvider type GCP

```
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: gcp
  namespace: capg-system
spec:
  configSecret:
    name: gcp-credentials-qmyxt
  credentials:
      rancherCloudCredentialNamespaceName: cattle-global-data:cc-4w8r5
  name: gcp
  variables:
    CLUSTER_TOPOLOGY: "true"
    EXP_CLUSTER_RESOURCE_SET: "true"
  type: infrastructure
```
**Logs**

```
E0425 07:36:38.279512       1 controller.go:329]  "msg"="Reconciler error" "error"="action failed after 10 attempts: failed to create provider object /v1, Kind=Secret, capg-system/capg-manager-bootstrap-credentials: Secret in version \"v1\" cannot be handled as a Secret: json: cannot unmarshal object into Go struct field Secret.data of type []uint8" "InfrastructureProvider"={"name":"gcp","namespace":"capg-system"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="gcp" "namespace"="capg-system" "reconcileID"="bd6cd108-c507-4983-a48e-cd60f1947495"
I0425 07:36:38.279573       1 genericprovider_controller.go:62]  "msg"="Reconciling provider" "InfrastructureProvider"={"name":"gcp","namespace":"capg-system"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="gcp" "namespace"="capg-system" "reconcileID"="5d107bdd-f960-4453-bb36-6dac5135c9d4"
```

### What did you expect to happen?

Enabling GCP CAPIProvider with Rancher CloudCredentials must complete successfully

### Rancher Turtles version

Turtles: v0.6.0

### Anything else you would like to add?

It seems GCP_B64ENCODED_CREDENTIALS from Cloud credentials is not getting encoded:
```
$ kubectl get secret/gcp-credentials-qmyxt -n capg-system --template={{.data.GCP_B64ENCODED_CREDENTIALS}}  | base64 -d
{
  "type": "service_account",
  "project_id": "<REDACTED>",
  "private_key_id": "<REDACTED>",
  "private_key": "-----BEGIN PRIVATE KEY-----<REDACTED>-----END PRIVATE KEY-----",
  "client_email": "<REDACTED>",
  "client_id": "<REDACTED>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "<REDACTED>"
}
```

### Label(s) to be applied

/kind bug
