### ISSUE TITLE
Implement runtime extension mechanism for credentials syncronization

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#530]
### What would you like to be added (User Story)?

As an operator I’d like to use rancher credentials in `ClusterClass` templating process, so I don’t have to specify credential secrets twice.

### Detailed Description

[Runtime extension](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook) feature allows to define logic for variable templating within `ClusterClass` definition. With our credentials syncing mechanism, this would allow us to specify a simple `patches:` definition in provided ClusterClasses or require users to define it in user provided ClusterClasses in the lines of:
```yaml
    # External patch definitions.
    patches:
    - name: credentialRepository
      external:
          generateExtension: generate-patches.turtles-credentials
          validateExtension: validate-topology.turtles-credentials
          ## Call variable discovery for this patch.
          discoverVariablesExtension: discover-variables.turtles-credentials
```
which will automate credential templating for them during `Cluster` creation, similar to:
```yaml

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
#metadata 
spec:
  topology:
    variables:
      - name: azure-credentials
        definitionFrom: credentialRepository
        value: “AZURE_TENANT_ID”
… # Other variable definitions
```

### Label(s) to be applied

/kind feature
