### ISSUE TITLE
Incorrect Image specification for CAPIProvider

### ISSUE THREAD

**Issue by MAXxATTAXx** [rancher/turtles#532]
### What steps did you take and what happened?

Installed rancher-turtles helm chart with default values. When inspecting the generated CAPIProvider they are generated with the following:

```YAML
---
# Source: rancher-turtles/templates/core-provider.yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: cluster-api
  namespace: capi-system
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  name: cluster-api
  type: core
  version: 
  additionalManifests:
    name: capi-additional-rbac-roles
    namespace: capi-system
  configSecret:
    name: capi-env-variables
  deployment:
    containers:
      - name: manager
        image: registry.rancher.com/rancher/rancher/turtles
---
# Source: rancher-turtles/templates/rke2-bootstrap.yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-bootstrap
  namespace: rke2-bootstrap-system
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  name: rke2
  type: bootstrap
  configSecret:
    name: capi-env-variables
  deployment:
    containers:
      - name: manager
        image: registry.rancher.com/rancher/rancher/turtles
---
# Source: rancher-turtles/templates/rke2-controlplane.yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-control-plane
  namespace: rke2-control-plane-system
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  name: rke2
  type: controlPlane
  configSecret:
    name: capi-env-variables
  deployment:
    containers:
      - name: manager
        image: registry.rancher.com/rancher/rancher/turtles
```

`image` field is not the correct syntax for overwritting the image for a provider. Also by default it overwrites the image for all those Providers to use rancher/turtles image instead of the provider specific controller.

### What did you expect to happen?

The correct syntax of a Provider that will overwrite the default image should be:

```YAML
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: rke2-control-plane
  namespace: rke2-control-plane-system
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  name: rke2
  type: controlPlane
  configSecret:
    name: capi-env-variables
  deployment:
    containers:
      - name: manager
        imageUrl: registry.rancher.com/rancher/rancher/turtles # Correct Overwrite
```

### How to reproduce it?

helm template rancher-turtles helm/helm-rancher-turtles/rancher-turtles --version 0.7.0 -n rancher-turtles-system > template.yaml

### Rancher Turtles version

v0.7.0

### Label(s) to be applied

/kind bug
