### ISSUE TITLE
Unable to update custom CAPIProvider version

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#758]
### What steps did you take and what happened?

- Install turtles v0.11.0 on Rancher v2.9 via Rancher Dashboard
- Install custom providers eg. 
1. kubeadm-control-plane using YAML (do not provide version)
2. kubeadm-bootstrap using CAPI-UI extension, it creates using version
```
spec:
  configSecret:
    name: custom-credentials-xtczv
  features:
    clusterResourceSet: true
    clusterTopology: true
    machinePool: true
  fetchConfig:
    url: >-
      https://github.com/kubernetes-sigs/cluster-api/releases/v1.4.6/bootstrap-components.yaml
  name: kubeadm
  type: bootstrap
  variables: {}
  **version: v1.4.6**
```

![image](https://github.com/user-attachments/assets/1f85e637-bb61-4693-9175-15818e6d0820)

- Upgrade turtles to v0.12

kubeadm-control-plane is auto-upgraded to v1.7.3
`message: Updated to latest v1.7.3 version`

kubeadm-bootstrap stays on v1.4.6 and unable to upgrade using ClusterctlConfig
`message: Provider version update available. Current latest is v1.7.3`

### What did you expect to happen?

CAPIProvider version should be auto-upgraded or User able to upgrade custom CAPIProvider version

### Rancher Turtles version

v.0.12

### Label(s) to be applied

/kind bug

**Comment by salasberryfin** [comment]
Thanks for reporting this @cpinjani and for helping me out with reproducing it. I was able to experience the behavior described in the issue. Since user provided a specific version during provider installation I think it would make sense that they are required to manually update to a newer version, as automatic updates may not align with their needs.

In this case I managed to update the version manually by editing the `CAPIProvider` resource, which I think should be the source of truth in this situation. Perhaps what is missing here is a way to let users know that there are newer versions available and a way for them to update the provider via UI, equivalent to what we have in Turtles. What do you think?

![image](https://github.com/user-attachments/assets/24162b6c-2917-4dd5-b8e6-7be1963e101f)
 

For cases where user did not configure a specific version, it's sensible that Turtles takes care of applying latest version available.

**Comment by cpinjani** [comment]
@salasberryfin Users get message that there are newer versions available from CAPIProvider status.
Agreed there should be a way for them to get informed & update the provider via UI similar to below.

![image](https://github.com/user-attachments/assets/fe2ec9cb-5d9f-444b-919b-8912bbf3d5c3)

```
status:
  conditions:
    - lastTransitionTime: '2024-11-08T06:44:05Z'
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Ready
    - lastTransitionTime: '2024-11-08T07:01:20Z'
      message: Provider version update available. Current latest is v1.7.7
      reason: UpdateAvailable
      severity: Info
      status: 'False'
      type: CheckLatestVersionTime
```
