### ISSUE TITLE
Support deduplication when using `ClusterctlConfig`

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#761]
### What would you like to be added (User Story)?

As a user, I would like to be able to override values in existing providers, e.g. changing the URL, via `ClusterctlConfig`.

### Detailed Description

With the current implementation of `ClusterctlConfig` it is possible to add new providers to the list contained in the `ConfigMap` that represents `clusterctl.yaml`. This is great for providers like Metal3, which can be added with a given URL via the resource. If needing to override values of a provider that already exists in the `ConfigMap`, e.g. the URL for an air-gapped environment, the `ClusterctlConfig` is not able to deduplicate the data provided in the resource and will add the new configuration to the bottom of the list.

### Anything else you would like to add?

This is a truncated version of the content of the `ConfigMap`:
```yaml
apiVersion: v1
data:
  clusterctl.yaml: |
    images: {}
    providers:
    - name: cluster-api
      type: CoreProvider
      url: https://github.com/rancher-sandbox/cluster-api/releases/v1.7.3/core-components.yaml
    - name: aws
      type: InfrastructureProvider
      url: https://github.com/rancher-sandbox/cluster-api-provider-aws/releases/v2.6.1/infrastructure-components.yaml
    - name: azure
      type: InfrastructureProvider
      url: https://github.com/rancher-sandbox/cluster-api-provider-azure/releases/v1.16.1/infrastructure-components.yaml
```
Suppose we would like to modify CAPA's URL via:
```yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: rancher-turtles-system
spec:
  providers:
  - name: aws
    url: https://github.com/kubernetes-sigs/cluster-api/releases/v1.7.3/core-components.yaml
    type: InfrastructureProvider
```
The resulting `ConfigMap` will contain duplicated entries for AWS provider.

As a user, I would like this to be able to identify an existing entry and update its content.

### Label(s) to be applied

/kind feature

**Comment by thehejik** [comment]
**Tests report**
* rancher v2.10-head
* turtles image and chart built from git commit `4815395eecb7e5cb36e74a53bfec5e6c784110f0`.

I was able to override origin of images used in `control-plane-rke2` and `bootstrap-rke2` providers. By running this.
```
cat << EOF| kubectl apply -f - 
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: rancher-turtles-system
spec:
  images:
    - name: control-plane-rke2
      repository: docker.io/thehejik
      tag: v0.11.0
    - name: bootstrap-rke2
      repository: docker.io/thehejik
      tag: v0.11.0
EOF
```
NOTE: I was a bit struggling with that the image name is actually not part of `repository:` value, it consists just from  the registry/directory part, the image itself has to have original name like `cluster-api-provider-rke2-controlplane` and `cluster-api-provider-rke2-bootstrap`. The tag can be changed.
