### ISSUE TITLE
CAPIProvider: secret is not assigned by default

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#787]
### What steps did you take and what happened?

Create a minimal `CAPIProvider` template:
```yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: azure
  namespace: capz-system
spec:
  type: infrastructure
```

### What did you expect to happen?

Default set of FG to be set. None are set by default, due to generated secret not being referenced in the underlying `InfrastructurProvider` resource, created from the supplied template.

For each provider (at the time of issue creation) the default set consists of:
```yaml
EXP_CLUSTER_RESOURCE_SET: true
CLUSTER_TOPOLOGY: true
EXP_MACHINE_POOL: true
```

Each value can be overridden with `spec.features` or `spec.variables`, but requiring these values to be always present is creating inconsistencies with e2e scenarios and real world cluster template examples. A user is not supposed to read `test/e2e` templates first, to create a provider and get a `Cluster`.

### How to reproduce it?

Always

### Label(s) to be applied

/kind bug
