### ISSUE TITLE
CAPIProvider infinite secret reconciliation loop

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#914]
This can be reproduced with the following manifest. 
The CAPIProviderController is trying to reconcile the syncing provider secret on an infinite loop somehow:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: capiprovider-test
spec: {}
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: digitalocean
  namespace: capiprovider-test
spec:
  credentials: 
    rancherCloudCredential: digitalocean-test-secret
  type: infrastructure
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    field.cattle.io/name: "digitalocean-test-secret"
    provisioning.cattle.io/driver: "digitalocean"
  name: cc-digitalocean
  namespace: cattle-global-data
data:
  digitaloceancredentialConfig-accessToken: dG9rZW4K
```

_Originally posted by @anmazzotti in https://github.com/rancher/turtles/issues/892#issuecomment-2519960132_
